# 日志配置
log:
  # 日志路径
  path: ./logs
  # 日志最大的历史
  max-history: 730

server:
  port: 8181
spring:
  application:
    name: @artifactId@
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
  #国际化资源文件
  messages:
    basename: i18n/message,i18n/user_message
  web:
    resources:
      static-locations: classpath:static/


#okHttpClient配置
ok:
  http:
    #最大空闲连接数
    max-idle-connections: 500
    #保活持续时间 分钟
    keep-alive-duration: 5
    #以下单位 秒
    connect-timeout: 10
    read-timeout: 10
    write-timeout: 10

#coco配置
coco:
  # 请求L站 state 过期时间 分钟
  expirationTtl: 5
  #重定向地址
  redirectUri:
  clientId:
  clientSecret:
  #  L站
  authorizationEndpoint:
  tokenEndpoint:
  userEndpoint:
  #代理节点
  baseApi:
  baseProxy:
  #ghu 频率秒  1秒8次
  frequencyTime: 1
  #ghu频率数
  frequencyDegree: 8
  #用户基础频率  1分钟10次
  userRateTime: 1
  #用户基础频率数
  userFrequencyDegree: 10
  #用户token 有效期无请求接口 小时
  userTokenExpire: 1
  #允许用户的最低等级等级
  userLevel: 2


#以下为风控参数
risk-contr:
  # 一个账号 一天能获取多少次Token
  getTokenNum: 10
  #单token 成功请求的最大数量 * 倍率 token失效
  tokenMaxReq: 500
  #每天用户最大请求数量 *倍率  限制 10小时 不可登陆
  userMaxReq: 2000
  userMaxTime: 10
  #超出用户最大访问速率
  #10次 该用户访问频率为  基础 * 0.5倍
  tokenInvalidNum: 10
  #30次  token失效  2小时不可登陆
  rejectTimeNum: 30
  rejectTime: 2
  #ban级别  触发 5 次上面 reject 限制 封号
  banNum: 5

#redis 配置
redisson:
  mode: single
  database: 1
  password:
  single:
    address: redis://127.0.0.1:6379
  cluster:
    master-connection-pool-size: 64
    nodes: redis://127.0.0.1:7004,redis://127.0.0.1:7001,redis://127.0.0.1:7000
    retry-attempts: 3
    retry-interval: 1500
    scan-interval: 1000
    slave-connection-pool-size: 64
  sentinel:
    nodes: redis://127.0.0.1:7004,redis://127.0.0.1:7001,redis://127.0.0.1:7000
    master: business-master
    master-onlyWrite: true
  timeout: 3000
  read-mode: SLAVE
  subscription-mode: SLAVE
  pool:
    conn-timeout: 3000
    min-idle: 24
    size: 24
    so-timeout: 3000

