server:
  port: 8181
spring:
  application:
    name: @artifactId@
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
  #国际化资源文件
  messages:
    basename: i18n/message,i18n/user_message
  web:
    resources:
      static-locations: classpath:static/
  redisson:
    file: 'file:/app/conf/redisson-config.yml'


#okHttpClient配置
ok:
  http:
    #最大空闲连接数
    max-idle-connections: 500
    #保活持续时间 分钟
    keep-alive-duration: 5
    #以下单位 秒
    connect-timeout: 10
    read-timeout: 10
    write-timeout: 10

#coco配置
coco:
  # 请求L站 state 过期时间 分钟
  expirationTtl: ${COCO_EXPIRATION_TTL:5}
  #重定向地址
  redirectUri: ${COCO_REDIRECT_URI}
  clientId: ${COCO_CLIENT_ID}
  clientSecret: ${COCO_CLIENT_SECRET}
  #  L站
  authorizationEndpoint: ${COCO_AUTHORIZATION_ENDPOINT}
  tokenEndpoint: ${COCO_TOKEN_ENDPOINT}
  userEndpoint: ${COCO_USER_ENDPOINT}
  #代理节点
  baseApi: ${COCO_BASE_API}
  baseProxy: ${COCO_BASE_PROXY}
  #ghu 频率秒  1秒8次
  frequencyTime: ${COCO_FREQUENCY_TIME:1}
  #ghu频率数
  frequencyDegree: ${COCO_FREQUENCY_DEGREE:8}
  #用户基础频率  5秒1次
  userRateTime: ${COCO_USER_RATE_TIME:5}
  #用户基础频率数
  userFrequencyDegree: ${COCO_USER_FREQUENCY_DEGREE:1}
  #用户token 有效期无请求接口 小时
  userTokenExpire: ${COCO_USER_TOKEN_EXPIRE:1}
  #允许用户的最低等级等级
  userLevel: ${COCO_USER_LEVEL:2}

